<?php defined('SYSPATH') OR die('No direct access allowed.');

return array(

	'uncountable' => array(
		'access',
		'advice',
		'art',
		'baggage',
		'contact_brochures',
		'contact_connects',
		'contact_contacts',
		'contact_customerservices',
		'contact_demos',
		'contact_feedbacks',
		'contact_tours',
		'dances',
		'equipment',
		'fish',
		'fuel',
		'furniture',
		'food',
		'heat',
		'hello',
		'honey',
		'homework',
		'impatience',
		'information',
		'knowledge',
		'luggage',
		'money',
		'music',
		'news',
		'patience',
		'progress',
		'poll_answers',
		'poll_questions',
		'pollution',
		'research',
		'rice',
		'sand',
		'series',
		'sheep',
		'sms',
		'species',
		'staff',
		'toothpaste',
		'traffic',
		'understanding',
		'water',
		'weather',
		'work',
	),

	'irregular' => array(
		'child' => 'children',
		'clothes' => 'clothing',
		'man' => 'men',
		'movie' => 'movies',
		'person' => 'people',
		'woman' => 'women',
		'mouse' => 'mice',
		'goose' => 'geese',
		'ox' => 'oxen',
		'leaf' => 'leaves',
		'course' => 'courses',
		'size' => 'sizes',
		'was' => 'were',
		'is' => 'are',
	),
);
